# Generated by Django 2.1.3 on 2018-12-10 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infotienda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='redsocial',
            name='id_icon',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
