# Generated by Django 2.1.3 on 2018-12-10 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infotienda', '0002_redsocial_id_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='infotienda.Categorias', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='local',
            name='horario_de_atencion_fin_1',
            field=models.TimeField(verbose_name='Hora de cierre 1'),
        ),
        migrations.AlterField(
            model_name='local',
            name='horario_de_atencion_fin_2',
            field=models.TimeField(verbose_name='Hora de cierre 1'),
        ),
        migrations.AlterField(
            model_name='local',
            name='horario_de_atencion_inicio_1',
            field=models.TimeField(verbose_name='Hora de atención 1'),
        ),
        migrations.AlterField(
            model_name='local',
            name='horario_de_atencion_inicio_2',
            field=models.TimeField(verbose_name='Hora de atención 2'),
        ),
        migrations.AlterField(
            model_name='local',
            name='telefono',
            field=models.CharField(max_length=10, verbose_name='Teléfono'),
        ),
    ]
