# Generated by Django 2.1.3 on 2018-12-10 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infotienda', '0004_local_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenlocal',
            name='image',
            field=models.ImageField(upload_to='locales'),
        ),
        migrations.AlterField(
            model_name='local',
            name='imagen',
            field=models.ImageField(upload_to='locales'),
        ),
    ]
