# Generated by Django 2.1.3 on 2018-12-10 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infotienda', '0006_auto_20181210_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracioSitio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sitio', models.CharField(max_length=200)),
                ('favicon', models.ImageField(upload_to='favicon')),
                ('descripcion', models.TextField()),
                ('telefono', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('facebook', models.URLField()),
                ('twitter', models.URLField()),
                ('instagram', models.URLField()),
                ('meta_description', models.TextField()),
                ('meta_author', models.CharField(max_length=100)),
                ('meta_keywords', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Configuración de sitio',
                'verbose_name_plural': 'Configuraciones de sitio',
            },
        ),
    ]
