# Generated by Django 2.1.3 on 2018-12-10 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infotienda', '0007_configuraciositio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuraciositio',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='configuraciositio',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='configuraciositio',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='configuraciositio',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='configuraciositio',
            name='meta_author',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='configuraciositio',
            name='meta_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='configuraciositio',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='configuraciositio',
            name='telefono',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='configuraciositio',
            name='twitter',
            field=models.URLField(blank=True),
        ),
    ]
