# Generated by Django 2.1.3 on 2018-12-10 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infotienda', '0008_auto_20181210_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuraciositio',
            name='direccion',
            field=models.CharField(default='Latacunga', max_length=100),
            preserve_default=False,
        ),
    ]
