# Generated by Django 2.1.3 on 2018-12-10 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infotienda', '0009_configuraciositio_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='local',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=15, null=True),
        ),
    ]
