# Generated by Django 2.1.3 on 2018-12-10 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infotienda', '0010_auto_20181210_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'verbose_name': 'Email',
                'verbose_name_plural': 'Emails',
            },
        ),
        migrations.AlterModelOptions(
            name='categorias',
            options={'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterModelOptions(
            name='imagenlocal',
            options={'verbose_name': 'Imágen de locales', 'verbose_name_plural': 'Imágenes de locales'},
        ),
        migrations.AlterModelOptions(
            name='subcategorias',
            options={'verbose_name': 'Subcategoría', 'verbose_name_plural': 'Subcategorías'},
        ),
    ]
